connect:
    ip: 127.0.0.1
    db: localhost
    login: root
    password: password
message: |
    =*======================
    [{name}]
    -
    Звание: {rank}
    Уровень: {lvl}
    Здоровье: {hp}
    -
    Динарии: {money}
    Убито мобов: {mobs}
    Убито игроков: {players}
    Смертей: {deaths}
    =*======================