name: PlayerInfo
main: me.kapehh.PlayerInfo.Main
author: kapehh
version: 1.0.0
commands:
    playerinfo:
        description: PlayerInfo
        usage: /<command> [reload - for console, playername - for players]
        aliases: 'i'